import { Answers } from "./Answers";
import { SoftwareType } from "./Software";
import { HardwareType } from "./Hardware";
import { nodeModuleNameResolver } from "typescript";

export const answers: Answers = {
  "A1.1": "Safe Space One",
  "A1.2": "12345678",
  "A1.3": "Tec Marina\nPenarth\nCF64 1SA",
  "A1.4": "Software",
  "A1.5": "https://www.safespaceone.com",
  "A1.6": 16253,
  "A1.7": 1623,
  "A1.8": true,
  "A1.9": "Because...",
  "A1.10": false,
  "A2.6": [
    {
      name: "saleman",
      make: "hp",
      model: "omen",
      os: "windows",
      featureVersion: "0.1.1",
      location: "cafetteria",
      quantity: 3,
      purpose: "coffemaking",
      type: HardwareType.TabletAndMobile,
    },

    {
      name: "duddad",
      make: "hp",
      model: "omen",
      os: "windows",
      featureVersion: "0.1.1",
      location: "cafetteria",
      quantity: 1,
      purpose: "coffemaking",
      type: HardwareType.TabletAndMobile,
    },
  ],
  "A.2.6.1":[{
    name: "saleman",
    make: "hp",
    model: "omen",
    os: "windows",
    featureVersion: "0.1.1",
    location: "cafetteria",
    quantity: 3,
    purpose: "coffemaking",
    numberOfVirtuals:5,
    type: HardwareType.TabletAndMobile
  }],
  "A2.1": true,
  "A2.2": "Whatever",
  "A2.5": "Cardiff",
  "A2.8": [
    { name: "TNCAP", location: "Cardiff", purpose: "General use" },
    { name: "BT02", location: "Cardiff", purpose: "General use" },
  ],
  "A3.1": false,
  "A3.2": false,
  "A3.3": 90000000000,
  "A3.4": true,
  "A3.5": false,
  "A3.6": "Someone@someone.com",
  "A4.1": false,
  "A4.2": true,
  "A4.4": "Hell no!",
  "A4.5": false,
  "A4.5.1": true,
  "A4.6": "Lolz",
  "A4.7": true,
  "A4.8": true,
  "A4.9": true,
  "A4.10": false,
  "A4.11": false,
  "A4.12": [ { name: "Microsoft Bob", version: "2.1.1", type: SoftwareType.Firewall }, { name: "Microsoft Henry", version: "2.1.2", type: SoftwareType.Firewall } ],
  "A5.1": "Why not",
  "A5.2": false,
  "A5.3": true,
  "A5.4": true,
  "A5.5": true,
  "A5.6": true,
  "A5.7": true,
  "A5.8": true,
  "A5.9": false,
  "A5.10": false,
  "A6.1": false,
  "A6.2": false,
  "A6.2.1": [{ name: "Chrome", version: "1.1.2", type: SoftwareType.Browser}, {name: "AskJeevs", version: "0.0.8", type: SoftwareType.Browser}],
  "A6.2.2": [{ name: "Avira", version: "4.2", type: SoftwareType.MalwareProtection}, {name: "Norton", version: "2.3.2", type: SoftwareType.MalwareProtection}],
  "A6.2.3": [{ name: "Outlook", version: "2.0", type: SoftwareType.Email}, {name: "G-mail", version: "1.4", type: SoftwareType.Email}],
  "A6.2.4": [{ name: "Excel", version: "5.1", type: SoftwareType.Browser}, {name: "Word", version: "6.2", type: SoftwareType.Browser}],
  "A6.3": false,
  "A6.4": true,
  "A6.4.1": true,
  "A6.4.2": true,
  "6.5":true,
  "A6.5.1": true,
  "A6.5.2":"lelele",
  "A6.6":true,
  "A7.1":"lello",
  "A7.2":true,
  "A7.3":"meh",
  "A7.4":"turpe",
  "A7.5":"leolo",
  "A7.6":"porter",
  "A7.7":"insigne",
  "A7.8":true,
  "A7.9":true,
  "A7.10":false,
  "A7.11": true,
  "A8.1": true,
  "A8.2":true,
  "A8.3":true,
  "A8.4":true,
  "A8.5": "yes it is ",
  "A8.6": "tulip",

 
  
  
  

};
