/* questions */

import { Question } from "./Question";
import { QuestionType } from "./QuestionType";

export const questions: Array<Question> = [
  { id: "A1.1", type: QuestionType.Text, question: "What is your organisation's name (for companies: as registered with Companies House)?" },
  { id: "A1.2", type: QuestionType.Text, question: "What is your organisation's registration number (if you have one)?" },
  { id: "A1.3", type: QuestionType.TextArea, question: "What is your organisation's address (for companies: as registered with Companies House)?" },
  { id: "A1.4", type: QuestionType.Text, question: "What is your main business?" },
  { id: "A1.5", type: QuestionType.Url, question: "What is your website address?" },
  { id: "A1.6", type: QuestionType.Number, question: "What is the size of your organisation? " },
  { id: "A1.7", type: QuestionType.Number, question: "How many staff are home workers? " },
  { id: "A1.8", type: QuestionType.YesNo, question: "Is this application a renewal of an existing certification or is it the first time you have applied for certification?" },
  { id: "A1.9", type: QuestionType.Text, question: "What is your main reason for applying for certification?" },
  { id: "A1.10", type: QuestionType.YesNo, question: "Have you read the 'Cyber Essentials Requirements for IT Infrastructure' document?" },
  { id: "A2.1", type: QuestionType.YesNo, question: "Does the scope of this assessment cover your whole organisation? Please note: Your organisation is only eligible for free Cyber Insurance if your assessment covers your whole company, if you answer 'No' to this question you will not be invited to apply for insurance. " },
  { id: "A2.2", type: QuestionType.Text, question: "If it is not the whole organisation, then what scope description would you like to appear on your certificate and website?" },
  { id: "A2.5", type: QuestionType.Text, question: "Please describe the geographical locations of your business which are in the scope of this assessment." },
  { id: "A2.6", type: QuestionType.Other, question: "Please list the quantities of laptops, computers and virtual desktops within the scope of this assessment. You must include model and operating system version for all devices.  For Windows 10 devices the Edition and Feature version are also required.   " },
  { id: "A2.6.1", type: QuestionType.Other, question: "Please list the quantities of servers, virtual servers and virtual server hosts (hypervisor). You must include the operating system." },
  { id: "A2.7", type: QuestionType.Other, question: "Please list the quantities of tablets and mobile devices within the scope of this assessment. You must include model and operating system versions for all devices." },
  { id: "A2.8", type: QuestionType.Other, question: "Please provide a list of the networks that will be in the scope for this assessment" },
  { id: "A2.9", type: QuestionType.Other, question: "Please provide a list of network equipment that will be in scope for this assessment (including firewalls and routers). You must include make and model of each device listed.  " },
  { id: "A2.10", type: QuestionType.Text, question: "Please provide the name and role of the person who is responsible for managing the information systems in the scope of this assessment?" },
  { id: "A3.1", type: QuestionType.YesNo, question: "Is your head office domiciled in the UK and is your gross annual turnover less than £20m?" },
  { id: "A3.2", type: QuestionType.YesNo, optional: true, question: "If you have answered 'yes' to the last question then your company is eligible for the included cyber insurance if you gain certification. If you do not want this insurance element please opt out here. " },
  { id: "A3.3", type: QuestionType.Number, question: "What is your total gross revenue? Please provide figure to the nearest £100K. You only need to answer this question if you are taking the insurance. " },
  { id: "A3.4", type: QuestionType.YesNo, question: "Is the company or its subsidiaries any of the following: medical, call centre, telemarketing, data processing (outsourcers), internet service provider, telecommunications or an organisation regulated by the FCA? You only need to answer this question if you are taking the insurance. " },
  { id: "A3.5", type: QuestionType.YesNo, question: "Does the company have any domiciled operation or derived revenue from the territory or jurisdiction of Canada and / or USA? " },
  { id: "A3.6", type: QuestionType.Email, question: "What is the organisation email contact for the insurance documents? You only need to answer this question if you are taking the insurance.  " },
  { id: "A4.1", type: QuestionType.YesNo, question: "Do you have firewalls at the boundaries between your organisation’s internal networks and the internet?" },
  { id: "A4.2", type: "", question: "When you first receive an internet router or hardware firewall device it will have had a default password on it. Has this initial password been changed on all such devices? How do you ensure that the password has been changed?" },
  { id: "A4.3", type: "", question: "Is the new password on all your internet routers or hardware firewall devices at least 8 characters in length and difficult to guess?  " },
  { id: "A4.4", type: "", question: "Do you change the password when you believe it may have been compromised? How do you ensure that the password has been changed?" },
  { id: "A4.5", type: "", question: "Do you have any services enabled that can be accessed externally from your internet router or hardware firewall?" },
  { id: "A4.5.1", type: "", question: "Do you have a documented business case for all of these services? " },
  { id: "A4.6", type: "", question: "If you do have services enabled on your firewall, do you have a process to ensure they are disabled in a timely manner when they are no longer required?  Describe the process." },
  { id: "A4.7", type: "", question: "Have you configured your internet routers or hardware firewall devices so that they block all other services from being advertised to the internet? " },
  { id: "A4.8", type: "", question: "Are your internet routers or hardware firewalls configured to allow access to their configuration settings over the internet? " },
  { id: "A4.9", type: "", question: "If yes, is there a documented business requirement for this access?" },
  { id: "A4.10", type: "", question: "If yes, is the access to the settings protected by either two-factor authentication or by only allowing trusted IP addresses to access the settings? List which option is used." },
  { id: "A4.11", type: "", question: "Do you have software firewalls enabled on all of your computers, laptops and servers? " },
  { id: "A4.12", type: "", question: "If no, is this because software firewalls are not commonly available for the operating system you are using? Please list the operating systems." },
  { id: "A5.1", type: "", question: "Where you are able to do so, have you removed or disabled all the software that you do not use on your laptops, computers, servers, tablets and mobile phones? Describe how you achieve this." },
  { id: "A5.2", type: "", question: "Have you ensured that all your laptops, computers, servers, tablets and mobile devices only contain necessary user accounts that are regularly used in the course of your business?" },
  { id: "A5.3", type: "", question: "Have you changed the default password for all user and administrator accounts on all your laptops, computers, servers, tablets and smartphones to a non-guessable password of 8 characters or more?" },
  { id: "A5.4", type: "", question: "Do all your users and administrators use passwords of at least 8 characters? " },
  { id: "A5.5", type: "", question: "Do you run software that provides sensitive or critical information (that shouldn't be made public) to users across the internet? " },
  { id: "A5.6", type: "", question: "If yes, do you ensure all users of these services use a password of at least 8 characters and that your systems do not restrict the length of the password?" },
  { id: "A5.7", type: "", question: "If yes, do you ensure that you change passwords if you believe that they have been compromised?" },
  { id: "A5.8", type: "", question: "If yes, are your systems set to lockout after ten or fewer unsuccessful login attempts, or limit the number of login attempts to no more than ten within five minutes?" },
  { id: "A5.9", type: "", question: "If yes, do you have a password policy that guides all your users? " },
  { id: "A5.10", type: "", question: "Is 'auto-run' or 'auto-play' disabled on all of your systems?" },
  { id: "A6.1", type: "", question: "Are all operating systems and firmware on your devices supported by a supplier that produces regular fixes for any security problems? " },
  { id: "A6.2", type: "", question: "Are all applications on your devices supported by a supplier that produces regular fixes for any security problems? " },
  { id: "A6.2.1", type: "", question: "Please list your Internet Browser/s" },
  { id: "A6.2.2", type: "", question: "Please list your Malware Protection" },
  { id: "A6.2.3", type: "", question: "Please list your Email Applications installed on end user devices and server." },
  { id: "A6.2.4", type: "", question: "Please list all Office Applications that are used to create organisational data. " },
  { id: "A6.3", type: "", question: "Is all software licensed in accordance with the publisher’s recommendations?" },
  { id: "A6.4", type: "", question: "Are all high-risk or critical security updates for operating systems and firmware installed within 14 days of release?" },
  { id: "A6.4.1", type: "", question: "Are all updates applied for operating systems by enabling auto updates ?" },
  { id: "A6.4.2", type: "", question: "Where auto updates are not being used, how do you ensure all high-risk or critical security updates of all operating systems and firmware are applied within 14 days of release?" },
  { id: "A6.5", type: "", question: "Are all high-risk or critical security updates for applications (including any associated files and any plugins such as Java, Adobe Reader and .Net.) installed within 14 days of release?   " },
  { id: "A6.5.1", type: "", question: "Are all updates applied for applications by enabling auto updates?" },
  { id: "A6.5.2", type: "", question: "Where auto updates are not being used, how do you ensure all high-risk or critical security updates of all applications are applied within 14 days of release?" },
  { id: "A6.6", type: "", question: "Have you removed any applications on your devices that are no longer supported and no longer receive regular fixes for security problems?" },
  { id: "A7.1", type: "", question: "Are users only provided with user accounts after a process has been followed to approve their creation? Describe the process." },
  { id: "A7.2", type: "", question: "Can you only access laptops, computers and servers in your organisation (and the applications they contain) by entering a unique user name and password?" },
  { id: "A7.3", type: "", question: "How do you ensure you have deleted, or disabled, any accounts for staff who are no longer with your organisation? " },
  { id: "A7.4", type: "", question: "Do you ensure that staff only have the privileges that they need to do their current job? How do you do this? " },
  { id: "A7.5", type: "", question: "Do you have a formal process for giving someone access to systems at an “administrator” level? Describe the process." },
  { id: "A7.6", type: "", question: "How do you ensure that administrator accounts are used only to carry out administrative tasks (such as installing software or making configuration changes)? " },
  { id: "A7.7", type: "", question: "How do you ensure that administrator accounts are not used for accessing email or web browsing?" },
  { id: "A7.8", type: "", question: "Do you formally track which users have administrator accounts in your organisation?" },
  { id: "A7.9", type: "", question: "Do you review who should have administrative access on a regular basis?" },
  { id: "A7.10", type: "", question: "Have you enabled two-factor authentication for access to all administrative accounts?" },
  { id: "A7.11", type: "", question: "If no, is this because two-factor authentication is not available for some or all of your devices or systems? List the devices or systems that do not allow two-factor authentication." },
  { id: "A8.1", type: "", question: "Are all of your computers, laptops, tablets and mobile phones protected from malware by either: A - having anti-malware software installed and/or: B - limiting installation of applications to an approved set (i.e. using an App Store and a list of approved applications) and/or: C - application sandboxing (i.e. by using a virtual machine)?" },
  { id: "A8.2", type: "", question: "(A) Where you have anti-malware software installed, is it set to update daily and scan files automatically upon access?" },
  { id: "A8.3", type: "", question: "(A) Where you have anti-malware software installed, is it set to scan web pages you visit and warn you about accessing malicious websites?" },
  { id: "A8.4", type: "", question: "(B) Where you use an app-store or application signing, are users restricted from installing unsigned applications? " },
  { id: "A8.5", type: "", question: "(B) Where you use an app-store or application signing, do you ensure that users only install applications that have been approved by your organisation and do you document this list of approved applications?" },
  { id: "A8.6", type: "", question: "(C) Where you use application sandboxing, do you ensure that applications within the sandbox are unable to access data stores, sensitive peripherals and your local network? Describe how you achieve this." },
];